language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm run test
after_script: # upload coverage reports to coveralls
  - COVERALLS_REPO_TOKEN=$coveralls_repo_token
  - npm run test:coveralls
